apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: api-evaluator
  name: api-evaluator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-evaluator
    spec:
      containers:
        - name: api-evaluator
          image: api_evaluator_poetisa
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
