apiVersion: v1
kind: Service
metadata:
  name: api-evaluator
  labels:
    app: api-evaluator
spec:
  selector:
    app: api-evaluator
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      nodePort: 30501
  type: "NodePort"
  # type: "LoadBalancer"
