apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: api-billing
  name: api-billing
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-billing
    spec:
      containers:
      - name: api-billing
        image: api_billing_poetisa
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

