apiVersion: v1
kind: Service
metadata:
  name: apiBilling
  labels:
    app: apiBilling
spec:
  selector:
    app: apiBilling
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30500
  type: "NodePort"
  