apiVersion: v1
kind: Service
metadata:
  name: api-billing
  labels:
    app: api-billing
spec:
  selector:
    app: api-billing
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30501
  type: "NodePort"
  # type: "LoadBalancer"
  